-- CREAR BASE DE DATOS
CREATE DATABASE APP_GESTION_BANCO;
USE APP_GESTION_BANCO;

-- TABLA PROVINCIAS
CREATE TABLE PROVINCIAS (
    ID_PROVINCIA VARCHAR(2) NOT NULL,
    DESCRIPCION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_PROVINCIA)
);

-- TABLA LOCALIDADES
CREATE TABLE LOCALIDADES (
    ID_LOCALIDAD VARCHAR(2) NOT NULL,
    ID_PROVINCIA VARCHAR(2) NOT NULL,
    DESCRIPCION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_LOCALIDAD),
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA)
);

-- TABLA TIPOS DE CUENTAS
CREATE TABLE TIPOS_CUENTAS (
    ID_TIPO_CUENTA  INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_TIPO_CUENTA )
);

-- TABLA TIPOS DE MOVIMIENTOS
CREATE TABLE TIPOS_MOVIMIENTOS (
    ID_TIPO_MOVIMIENTO INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TIPO_MOVIMIENTO)
);

-- TABLA CLIENTES
CREATE TABLE CLIENTES (
    DNI VARCHAR(8) NOT NULL,
    CUIL VARCHAR(11) NOT NULL UNIQUE,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL CHECK( SEXO IN ('M','F') ),
    NACIONALIDAD VARCHAR(30),
    FECHA_NACIMIENTO DATE NOT NULL,
    DIRECCION VARCHAR(50),
    ID_PROVINCIA VARCHAR(2),
    ID_LOCALIDAD VARCHAR(2),
    CORREO VARCHAR(50) NOT NULL UNIQUE,
    TELEFONO VARCHAR(12),
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (DNI),
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA),
    FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID_LOCALIDAD)
);

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    DNI_CLIENTE CHAR(8),
    NOMBRE_USUARIO VARCHAR(30) NOT NULL,
    CONTRASENIA VARCHAR(100) NOT NULL,
    ROL CHAR(1) NOT NULL CHECK(ROL IN ('A','C')),
    PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI)
);

-- TABLA CUENTAS
CREATE TABLE CUENTAS (
    NUMERO_CUENTA INT UNSIGNED AUTO_INCREMENT,
    DNI_CLIENTE VARCHAR(8) NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    ID_TIPO_CUENTA INT NOT NULL,
    CBU CHAR(22) NOT NULL UNIQUE,
    SALDO DECIMAL(15,2) NOT NULL DEFAULT 0,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (NUMERO_CUENTA),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI),
    FOREIGN KEY (ID_TIPO_CUENTA) REFERENCES TIPOS_CUENTAS(ID_TIPO_CUENTA),
    CHECK (SALDO >= 0)
);

-- TABLA PRESTAMOS
CREATE TABLE PRESTAMOS (
    ID_PRESTAMO INT AUTO_INCREMENT,
    DNI_CLIENTE VARCHAR(8) NOT NULL,
    NUMERO_CUENTA INT UNSIGNED NOT NULL,
    FECHA_PRESTAMO DATE NOT NULL,
    IMPORTE_TOTAL DECIMAL(15,2) NOT NULL,
    IMPORTE_SOLICITADO DECIMAL(15,2) NOT NULL,
    PLAZO_MESES INT NOT NULL,
    MONTO_MENSUAL DECIMAL(15,2) NOT NULL,
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('P','A','R')),

    PRIMARY KEY (ID_PRESTAMO),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI),
    FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTAS(NUMERO_CUENTA),
    CHECK (IMPORTE_TOTAL > 0),
    CHECK (IMPORTE_SOLICITADO > 0),
    CHECK (PLAZO_MESES > 0),
    CHECK (MONTO_MENSUAL > 0)
);

-- TABLA CUOTAS
CREATE TABLE CUOTAS (
    ID_CUOTA INT AUTO_INCREMENT,
    ID_PRESTAMO INT NOT NULL,
    NUMERO_CUENTA INT UNSIGNED NOT NULL,
    NUMERO_CUOTA INT NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MONTO_CUOTA DECIMAL(15,2) NOT NULL,
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('P','D')),

    PRIMARY KEY (ID_CUOTA),
    FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMOS(ID_PRESTAMO),
    FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTAS(NUMERO_CUENTA),
    CHECK (MONTO_CUOTA > 0),
    CHECK (NUMERO_CUOTA > 0)
);

-- TABLA MOVIMIENTOS
CREATE TABLE MOVIMIENTOS (
    ID_MOVIMIENTO INT NOT NULL AUTO_INCREMENT,
    FECHA_MOVIMIENTO DATE NOT NULL,
    DETALLE VARCHAR(100),
    IMPORTE DECIMAL(15,2) NOT NULL,
    NUMERO_CUENTA INT UNSIGNED,
    ID_TIPO_MOVIMIENTO INT NOT NULL,
    PRIMARY KEY (ID_MOVIMIENTO),
    FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTAS(NUMERO_CUENTA),
    FOREIGN KEY (ID_TIPO_MOVIMIENTO) REFERENCES TIPOS_MOVIMIENTOS(ID_TIPO_MOVIMIENTO)
);
